services:
  php:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: ${COMPOSE_PROJECT_NAME:-linters}_php:latest
    deploy:
      resources:
        limits:
          cpus: 1.99
          memory: 2G
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME:-linters}_php
    hostname: ${COMPOSE_PROJECT_NAME:-linters}_php
    ports:
      - '${PHP_FPM_PORT:-9001}:9000'
    volumes:
      - ../:/var/www
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app_network

networks:
  app_network:
    name: ${COMPOSE_PROJECT_NAME:-linters}_network
    driver: bridge