<?php

declare(strict_types=1);

namespace Linters\ConfigGenerator;

use Linters\Utils\ConfigurationLoader;
use Safe\Exceptions\FilesystemException;
use Symfony\Component\Filesystem\Path;

use function Safe\file_put_contents;

abstract class AbstractStubConfigGenerator implements ConfigGeneratorInterface
{
    public function __construct(protected ConfigurationLoader $loader = new ConfigurationLoader())
    {
    }

    /**
     * @throws FilesystemException
     */
    public function generate(string $targetPath): void
    {
        $content = $this->buildContent();
        file_put_contents($targetPath, $content);
    }

    abstract protected function getConfigFileName(): string;

    abstract protected function getToolName(): string;

    abstract protected function getConfigKey(): string;

    abstract protected function getDocumentationUrl(): string;

    protected function buildContent(): string
    {
        $targetDir = $this->loader->getComposerDir();
        $sourcePath = \dirname(__DIR__, 2) . '/configs/' . $this->getConfigFileName();
        $packagePath = Path::makeRelative($sourcePath, $targetDir);

        $toolName = $this->getToolName();
        $configKey = $this->getConfigKey();
        $docUrl = $this->getDocumentationUrl();

        return <<<PHP
<?php

declare(strict_types=1);

/**
 * {$toolName} configuration - generated by devwolk/linters
 *
 * DO NOT EDIT - this file is auto-generated.
 * Configuration is read from composer.json extra.linters.{$configKey}
 *
 * @see {$docUrl}
 */

return require __DIR__ . '/{$packagePath}';

PHP;
    }
}
