<?php

declare(strict_types=1);

namespace Linters\ConfigGenerator;

use Linters\Utils\ConfigurationLoader;

/**
 * Generator for composer-unused configuration files
 *
 * Creates a stub file that requires the package's composer-unused.php config.
 * The package config reads named-filters from composer.json at runtime.
 */
class ComposerUnusedConfigGenerator implements ConfigGeneratorInterface
{
    private const PACKAGE_CONFIG_PATH = 'vendor/devwolk/linters/configs/composer-unused.php';

    protected ConfigurationLoader $loader;

    public function __construct(?ConfigurationLoader $loader = null)
    {
        $this->loader = $loader ?? new ConfigurationLoader();
    }

    public function generate(string $targetPath): void
    {
        $content = $this->buildContent();
        file_put_contents($targetPath, $content);
    }

    protected function buildContent(): string
    {
        $packagePath = self::PACKAGE_CONFIG_PATH;

        return <<<PHP
<?php

declare(strict_types=1);

/**
 * composer-unused configuration - generated by devwolk/linters
 *
 * DO NOT EDIT - this file is auto-generated.
 * Configuration is read from composer.json extra.linters.composer-unused
 *
 * @see https://github.com/composer-unused/composer-unused
 */

return require __DIR__ . '/{$packagePath}';

PHP;
    }
}
