<?php

declare(strict_types=1);

namespace Linters\ConfigGenerator;

use Linters\Utils\ConfigurationLoader;
use Safe\Exceptions\DirException;
use Safe\Exceptions\FilesystemException;
use Symfony\Component\Filesystem\Path;

use function Safe\file_put_contents;

/**
 * Generator for Rector PHP configuration files.
 *
 * Creates a stub file that requires the package's rector.php config.
 * The package config reads paths/excludes from composer.json at runtime.
 */
class RectorConfigGenerator implements ConfigGeneratorInterface
{
    public function __construct(protected ConfigurationLoader $loader = new ConfigurationLoader())
    {
    }

    /**
     * @throws FilesystemException
     * @throws DirException
     */
    public function generate(string $targetPath): void
    {
        $content = $this->buildContent();
        file_put_contents($targetPath, $content);
    }

    /**
     * @throws DirException
     */
    protected function buildContent(): string
    {
        $targetDir = $this->loader->getComposerDir();
        $sourcePath = \dirname(__DIR__, 2) . '/configs/rector.php';

        $packagePath = Path::makeRelative($sourcePath, $targetDir);

        return <<<PHP
<?php

declare(strict_types=1);

/**
 * Rector configuration - generated by devwolk/linters
 *
 * DO NOT EDIT - this file is auto-generated.
 * Configuration is read from composer.json extra.linters.rector
 *
 * @see https://getrector.com/documentation
 */

return require __DIR__ . '/{$packagePath}';

PHP;
    }
}
