<?php

declare(strict_types=1);

namespace Linters\ConfigGenerator;

use Linters\Utils\ConfigurationLoader;

/**
 * Generator for Rector PHP configuration files
 *
 * Creates a stub file that requires the package's rector.php config.
 * The package config reads paths/excludes from composer.json at runtime.
 */
class RectorConfigGenerator implements ConfigGeneratorInterface
{
    private const PACKAGE_CONFIG_PATH = 'vendor/devwolk/linters/configs/rector.php';

    protected ConfigurationLoader $loader;

    public function __construct(?ConfigurationLoader $loader = null)
    {
        $this->loader = $loader ?? new ConfigurationLoader();
    }

    public function generate(string $targetPath): void
    {
        $content = $this->buildContent();
        file_put_contents($targetPath, $content);
    }

    protected function buildContent(): string
    {
        $packagePath = self::PACKAGE_CONFIG_PATH;

        return <<<PHP
<?php

declare(strict_types=1);

/**
 * Rector configuration - generated by devwolk/linters
 *
 * DO NOT EDIT - this file is auto-generated.
 * Configuration is read from composer.json extra.linters.rector
 *
 * @see https://getrector.com/documentation
 */

return require __DIR__ . '/{$packagePath}';

PHP;
    }
}
