<?php

declare(strict_types=1);

namespace Linters\ConfigGenerator\Contracts;

use Linters\Enum\Tool;
use Linters\Utils\ConfigurationLoader;
use Safe\Exceptions\FilesystemException;
use Symfony\Component\Filesystem\Path;

use function Safe\file_put_contents;

abstract class AbstractStubConfigGenerator implements ConfigGeneratorInterface
{
    private const string CONFIGS_DIR = __DIR__ . '/../../../configs/';

    public function __construct(
        private readonly Tool $tool,
        private readonly ConfigurationLoader $loader,
    ) {
    }

    /**
     * @throws FilesystemException
     */
    public function generate(string $targetPath): void
    {
        $content = $this->buildContent();
        file_put_contents($targetPath, $content);
    }

    protected function buildContent(): string
    {
        $sourceFileName = $this->tool->sourceConfigFileName();
        $targetDir = $this->loader->getComposerDir();
        $sourcePath = self::CONFIGS_DIR . $sourceFileName;
        $packagePath = Path::makeRelative($sourcePath, $targetDir);

        $toolName = $this->tool->label();
        $configKey = $this->tool->value;
        $docUrl = $this->tool->documentationUrl();

        return <<<PHP
<?php

declare(strict_types=1);

/**
 * {$toolName} configuration - generated by devwolk/linters
 *
 * DO NOT EDIT - this file is auto-generated.
 * Configuration is read from composer.json extra.linters.{$configKey}
 *
 * @see {$docUrl}
 */

return require __DIR__ . '/{$packagePath}';

PHP;
    }
}
