DOCKER_FILE := -f ./docker/docker-compose.yml

fix-syntax-completely: ## Fix code style by all code style instruments
	-@make syntax-fix
	-@make rector
	-@make php-cs-fixer
	-@make phpstan
	-@make composer-validate
	-@make composer-audit
	-@make test-unit

test-unit: ## Run unit tests
	docker-compose exec -T linters_fpm vendor/bin/phpunit -d memory_limit=512M --order-by=random --colors=always

syntax: ##  Check code style with php code sniffer tool
	docker-compose exec -T linters_fpm ./bin/linters run phpcs

syntax-fix: ## Fix code style with php code sniffer tool
	docker-compose exec -T linters_fpm ./bin/linters generate phpcs
	docker-compose exec -T linters_fpm vendor/bin/phpcbf -p --standard=phpcs.xml

rector: ## Fix code style with Rector tool
	docker-compose exec -T linters_fpm ./bin/linters run rector
rector-dry-run: ## Check code style with Rector tool
	docker-compose exec -T linters_fpm ./bin/linters generate rector
	docker-compose exec -T linters_fpm vendor/bin/rector process --config=rector.php --clear-cache --dry-run

php-cs-fixer: ## Fix code style with PHP-CS-Fixer tool
	docker-compose exec -T linters_fpm ./bin/linters run php-cs-fixer
php-cs-fixer-check: ## Check code style with PHP-CS-Fixer tool
	docker-compose exec -T linters_fpm ./bin/linters generate php-cs-fixer
	docker-compose exec -T linters_fpm vendor/bin/php-cs-fixer fix --dry-run --config=.php-cs-fixer.php --diff -vv --allow-risky=yes --using-cache=no

phpstan: ## Check code style with PHPStan tool
	docker-compose exec -T linters_fpm ./bin/linters run phpstan
phpstan-baseline: ## Check code style with PHPStan tool and generate baseline
	docker-compose exec -T linters_fpm ./bin/linters generate phpstan
	docker-compose exec -T linters_fpm vendor/bin/phpstan analyse --configuration=phpstan.neon --memory-limit=512M --generate-baseline --allow-empty-baseline -vv

composer-validate: ## Perform  composer.json and composer.lock validity analysis.
	docker-compose exec -T linters_fpm composer validate --no-check-all --no-check-publish --no-check-version
composer-audit: ## Outputs a list of reported security vulnerabilities for the list of packages versions currently installed.
	docker-compose exec -T linters_fpm composer audit
composer-unused: ## Find unused composer dependencies.
	docker-compose exec -T linters_fpm ./bin/linters run composer-unused
composer-normalize: ## Normalize composer.json and composer.lock files.
	docker-compose exec -T linters_fpm ./bin/linters run composer-normalize

config-generate: ## Generate config file
	printf "${COLOR_COMMENT}Generate config file...${COLOR_RESET}\n"
	echo "# DO NOT EDIT THIS FILE" > docker-compose.yml
	echo "# THIS FILE GENERATED AUTOMATICALLY" >> docker-compose.yml
	docker compose $(DOCKER_FILE) config >> docker-compose.yml
	printf "${COLOR_COMMENT}Done${COLOR_RESET}\n"
build: config-generate ## For initial build
	docker compose build --no-cache --pull --progress=plain
up: config-generate ## Up docker environment
	docker compose up -d --remove-orphans
down: ## Down docker environment
	docker compose down
stop: ## Stop docker environment
	docker compose stop
bash: ## Run bash console in Ubuntu based docker images.
	docker compose exec linters_fpm bash
